### ISSUE TITLE
Upload problem

### ISSUE THREAD

**Issue by mkoseoglu** [crowdAI/ieee_stock_prediction_challenge-starter-kit#5]
Hi all,
Today I have tried to upload a prediction for round 2 but the upload stalls as follows:

CrowdAI.Event.Authentication : Authenticating for challenge = IEEEInvestmentRankingChallenge
CrowdAI.Event.Connection.CONNECTED
CrowdAI.Event.Authentication.SUCCESS : Authentication Successful
CrowdAI.Event.Misc.FILE_UPLOAD : Preparing for file upload
CrowdAI.Event.Misc.FILE_UPLOAD : Uploading file
100% |██████████|[00:00<00:00]  164.10% /s] 
  0% |          |[00:00<?]  ?% /s] 

It never completes the second step. Thanks!

**Comment by bearstrikesback** [comment]
Same issue. From error log after stopping:

d:\program files\python\lib\site-packages\crowdai\challenges\ieee_investment_ranking_challenge.py in submit(self, filename, round)
     59                 [{
     60                     "file_key": file_key,
---> 61                     "round": round
     62                  }]
     63                 )[0]

**Comment by spMohanty** [comment]
@BearStrikesBack : did you update your crowdai client ? 
And then add the “round” = 2 arg to your code ? 

```python
challenge = crowdai.Challenge("IEEEInvestmentRankingChallenge", api_key)
result = challenge.submit("rf_starter_kit_predictions.csv", round=2)
```

**Comment by spMohanty** [comment]
@koseoglum : The grader was not live at that moment. Sorry, we should have posted a much more clear error message. But now you should be able to submit, by following the instructions here : https://github.com/crowdAI/ieee_investment_ranking_challenge-starter-kit#submission-of-predicted-file-to-crowdai

Note the `round=2` arg, and the updated crowdai package version.

**Comment by mkoseoglu** [comment]
Thanks @spMohanty! Yes, I have managed to resolve the issue by following the instructions there.
